production:
  client_id: 130636
  client_secret: e197c305cb
  account_id: 98354
  access_token: 9fe2dcdca5ec753dd17dba95e22ca3218dc796c002c4e987d9293f67febd5ba5
  root_callback_uri: "http://localhost:3000"
  after_checkout_redirect_uri: "http://localhost:3000/wepay/test"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_api_uri: "https://www.wepay.com/v2"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  auto_capture: true
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
development:
  client_id: 130636
  client_secret: e197c305cb
  account_id: 98354
  access_token: bf2f90b3fee4e438d68d5954325a230b9db1b6c833e55ffd63
  root_callback_uri: "http://localhost:3000"
  after_checkout_redirect_uri: "http://localhost:3000/wepay/test"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_api_uri: "https://stage.wepay.com/v2"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  auto_capture: true
  require_shipping: false
  shipping_fee: 0
  charge_tax: false
test:
  client_id: 130636
  client_secret: e197c305cb
  account_id: 98354
  access_token: 9fe2dcdca5ec753dd17dba95e22ca3218dc796c002c4e987d9293f67febd5ba5
  root_callback_uri: "http://localhost:3000"
  after_checkout_redirect_uri: "http://localhost:3000/wepay/test"
  scope: [refund_payments,collect_payments,view_balance,view_user]
  wepay_api_uri: "https://stage.wepay.com/v2"
  fee_payer: Payee
  checkout_type: GOODS
  charge_tax: false
  app_fee: 0
  auto_capture: true
  require_shipping: false
  shipping_fee: 0
  charge_tax: false

