require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WishlistItemsController do

  # This should return the minimal set of attributes required to create a valid
  # WishlistItem. As you add validations to WishlistItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WishlistItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wishlist_items as @wishlist_items" do
      wishlist_item = WishlistItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wishlist_items).should eq([wishlist_item])
    end
  end

  describe "GET show" do
    it "assigns the requested wishlist_item as @wishlist_item" do
      wishlist_item = WishlistItem.create! valid_attributes
      get :show, {:id => wishlist_item.to_param}, valid_session
      assigns(:wishlist_item).should eq(wishlist_item)
    end
  end

  describe "GET new" do
    it "assigns a new wishlist_item as @wishlist_item" do
      get :new, {}, valid_session
      assigns(:wishlist_item).should be_a_new(WishlistItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested wishlist_item as @wishlist_item" do
      wishlist_item = WishlistItem.create! valid_attributes
      get :edit, {:id => wishlist_item.to_param}, valid_session
      assigns(:wishlist_item).should eq(wishlist_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WishlistItem" do
        expect {
          post :create, {:wishlist_item => valid_attributes}, valid_session
        }.to change(WishlistItem, :count).by(1)
      end

      it "assigns a newly created wishlist_item as @wishlist_item" do
        post :create, {:wishlist_item => valid_attributes}, valid_session
        assigns(:wishlist_item).should be_a(WishlistItem)
        assigns(:wishlist_item).should be_persisted
      end

      it "redirects to the created wishlist_item" do
        post :create, {:wishlist_item => valid_attributes}, valid_session
        response.should redirect_to(WishlistItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wishlist_item as @wishlist_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        WishlistItem.any_instance.stub(:save).and_return(false)
        post :create, {:wishlist_item => {}}, valid_session
        assigns(:wishlist_item).should be_a_new(WishlistItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WishlistItem.any_instance.stub(:save).and_return(false)
        post :create, {:wishlist_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wishlist_item" do
        wishlist_item = WishlistItem.create! valid_attributes
        # Assuming there are no other wishlist_items in the database, this
        # specifies that the WishlistItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WishlistItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => wishlist_item.to_param, :wishlist_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested wishlist_item as @wishlist_item" do
        wishlist_item = WishlistItem.create! valid_attributes
        put :update, {:id => wishlist_item.to_param, :wishlist_item => valid_attributes}, valid_session
        assigns(:wishlist_item).should eq(wishlist_item)
      end

      it "redirects to the wishlist_item" do
        wishlist_item = WishlistItem.create! valid_attributes
        put :update, {:id => wishlist_item.to_param, :wishlist_item => valid_attributes}, valid_session
        response.should redirect_to(wishlist_item)
      end
    end

    describe "with invalid params" do
      it "assigns the wishlist_item as @wishlist_item" do
        wishlist_item = WishlistItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WishlistItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => wishlist_item.to_param, :wishlist_item => {}}, valid_session
        assigns(:wishlist_item).should eq(wishlist_item)
      end

      it "re-renders the 'edit' template" do
        wishlist_item = WishlistItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WishlistItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => wishlist_item.to_param, :wishlist_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wishlist_item" do
      wishlist_item = WishlistItem.create! valid_attributes
      expect {
        delete :destroy, {:id => wishlist_item.to_param}, valid_session
      }.to change(WishlistItem, :count).by(-1)
    end

    it "redirects to the wishlist_items list" do
      wishlist_item = WishlistItem.create! valid_attributes
      delete :destroy, {:id => wishlist_item.to_param}, valid_session
      response.should redirect_to(wishlist_items_url)
    end
  end

end
